# docker-compose for hassio: https://www.home-assistant.io/docs/installation/docker/
version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./hassio_config:/config
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyUSB1:/dev/ttyUSB1
    #   - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - TZ=America/New_York
    restart: always
    network_mode: host

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
        - ./nginx/reverseproxy.conf:/etc/nginx/conf.d/reverseproxy.conf
    ports:
      - 80:80
      - 443:443