# docker-compose for hassio: https://www.home-assistant.io/docs/installation/docker/
version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant:latest
    volumes:
      - ./hassio_config:/config
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyUSB1:/dev/ttyUSB1
    #   - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - TZ=America/New_York
    restart: always
    network_mode: host

  homeassistant_supervisor:
    container_name: hassio_supervisor
    image: homeassistant/armv7-hassio-supervisor:latest
    volumes:
      - ./hassio_config:/data


  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
        - ./nginx/reverseproxy.conf:/etc/nginx/conf.d/reverseproxy.conf
    ports:
      - 80:80
<<<<<<< HEAD
      - 443:443Yuan 
=======
      - 443:443
>>>>>>> 956550d642f643b4676515affe89317b65aa0136
